### ISSUE TITLE
Incorrect mod.yml

### ISSUE THREAD

**Issue by ColossusSteppes** [Mikote111/BBSOGTitleScreen#1]
The mod.yml seems to be formatted incorrectly, causing the mod to be skipped on OpenKH.

Replacing it with one that OpenKH generated from the .bbspcpatch on Nexusmods seems to fix it. The contents of the working mod.yml are below.

```
title: HD OG Title Screen
originalAuthor: Mikote111
description: Replaces the title screens with upscaled PSP versions.
game: bbs
dependencies: 
assets:
- name: raw\arc\menu\title_03.arc
  method: copy
  platform: pc
  package: bbs_first
  source:
  - name: raw\arc\menu\title_03.arc
- name: raw\arc\menu\title_v.arc
  method: copy
  platform: pc
  package: bbs_first
  source:
  - name: raw\arc\menu\title_v.arc
- name: raw\arc\menu\title_a.arc
  method: copy
  platform: pc
  package: bbs_third
  source:
  - name: raw\arc\menu\title_a.arc
- name: raw\arc\menu\title_t.arc
  method: copy
  platform: pc
  package: bbs_third
  source:
  - name: raw\arc\menu\title_t.arc
```
